# Синхронный код

Синхронный код понятный, его удобно читать, потому что он выполняется ровно так, как написан:
```javascript
console.log("A")
console.log("B")
console.log("C")

```

---

# Асинхронный код

Асинхронный код - код, который не блокирует основной поток выполнения команд

```javascript
setTimeout(function greet() {
  console.log("Hello!")
}, 5000)

```
> `setTimeout` это не `javascript` !
---


# Колбэки 

`Callback` (колбэк, функция обратного вызова) — функция, которая вызывается в ответ на совершение некоторого события.

```javascript
setTimeout(function greet() {
  console.log("Hello!")
}, 5000)

```
> колбэк — это первый способ обработать какое-либо асинхронное действие.

> Однако у колбэков есть неприятный минус

---

# Ад колбэков (Callback-hell)


```javascript
loadScript('1.js', function(error, script) {

  if (error) {
    handleError(error);
  } else {
    // ...
    loadScript('2.js', function(error, script) {
      if (error) {
        handleError(error);
      } else {
        // ...
        loadScript('3.js', function(error, script) {
          if (error) {
            handleError(error);
          } else {
            // ...и так далее, пока все скрипты не будут загружены (*)
          }
        });

      }
    })
  }
});
```

---

# Промисы 

Промис (Promise) — специальный объект JavaScript, который используется для написания и обработки асинхронного кода.

Асинхронные функции возвращают объект Promise в качестве значения. Внутри промиса работает асинхронная операция, которая управляет его состоянием.

Промис может находиться в одном из трёх состояний:

- `pending` — стартовое состояние, операция стартовала
- `fulfilled` — получен результат
- `rejected` — ошибка

> Поменять можно состояние только один раз: перейти из `pending` либо в `fulfilled`, либо в `rejected`:

У промиса есть методы `then` и `catch`, которые позволяют выполнять код при изменении его состояния.

---

# Создание 

Промис создаётся с помощью конструктора (т.е. использутеся ключевое слово `new`).

В конструктор передаётся функция-исполнитель асинхронной операции . Она вызывается сразу после создания промиса. Задача этой функции — выполнить асинхронную операцию и перевести состояние промиса в `fulfilled` (успех) или `rejected` (ошибка).

```javascript
const promise = new Promise(function (resolve, reject) {
  // делаем асинхронную операцию
  const data = resolve(data) // запрос в БД, API, etc. // переводим промис в состояние fulfilled и отдаём наружу результат операции
})

const errorPromise = new Promise(function (resolve, reject) {
  reject(new Error("ошибка")) // переводим промис в состояние rejected и отдаём наружу ошибку
})

```

Аргументы: 

- `resolve` — колбэк для перевода промиса в состояние `fulfilled`, при его вызове аргументом передаётся результат операции.
- `reject` — колбэк для перевода промиса в состояние `rejected`, при его вызове аргументом передаётся информация об ошибке

---

# Использование 

В работе мы чаще используем промисы, чем создаём. Использовать промис — значит выполнять код при изменении состояния промиса.

Существует три метода, которые позволяют реагировать на изменение промиса: 

- `then`
- `catch`
- `finally`

---

# then

Метод `then` используют, чтобы выполнить код после успешного выполнения асинхронной операции.

Метод `then` принимает в качестве аргумента `функцию-колбэк`, которая выполняется сразу после того, как промис поменял состояние на `fulfilled`. Параметр колбэка содержит результат выполнения операции:

```javascript
fetch(`https://swapi.dev/api/films/${id}/`).then(function (movies) {
  renderList(movies)
})
```

---

# catch

Метод `catch` используют, чтобы выполнить код в случае ошибки при выполнении асинхронной операции.

Метод `catch` принимает в качестве аргумента функцию-колбэк, которая выполняется сразу после того, как промис поменял состояние на `rejected`. Параметр колбэка содержит экземпляр ошибки:

```javascript
fetch(`https://swapi.dev/api/films/${id}/`).catch(function (error) {
  renderErrorMessage(error)
})
```

---

# finally

Метод `finally` используют, чтобы выполнить код при завершении асинхронной операции. Он будет выполнен вне зависимости от того, была ли операция успешной или завершилась ошибкой.

Метод `finally` принимает в качестве аргумента функцию-колбэк, которая выполняется сразу после того, как промис поменял состояние на `rejected`, или `fulfilled`:

```javascript
let isLoading = true
fetch(`https://swapi.dev/api/films/${id}/`).finally(function () {
  isLoading = false
})

```

---

# Цепочки методов

Методы `then`, `catch` и `finally` часто объединяют в цепочки вызовов для того, чтобы обработать и успешный, и ошибочный сценарий

```javascript
let isLoading = true

fetch(`https://swapi.dev/api/films/${id}/`)
  .then(function (movies) {
    renderList(movies)
  })
  .catch(function (err) {
    renderErrorMessage(err)
  })
  .finally(function () {
    isLoading = false
  })

```

---

# Цепочки методов

Цепочки методов — очень гибкий подход. Он позволяет создавать зависимые асинхронные операции.

Например, нужно отобразить информацию о фильме и главном герое. Мы не знаем, кто главный герой, не получив эту информацию из данных о фильме. Запрос данных о герое зависит от результата запроса данных о фильме.

Промисы делают решение такой задачи простым и читаемым. Мы можем начинать следующее асинхронное действие внутри колбэка метода `then`. Все, что возвращается из колбэка, оборачивается в промис, поэтому в цепочку можно добавить новый `then`:

```javascript
fetch(`https://swapi.dev/api/films/${id}/`)
  .then(function (response) {
    // этот then сработает, когда разрешится промис с запросом данных о фильме
    return response.json() // нужно распарсить ответ сервера, это асинхронная операция
  })
  .then(function (movie) {
    // этот then сработает, когда данные о фильме распарсятся
    const characterUrl = movie.characters[0]
    return fetch(characterUrl) // вызов fetch вернет промис, возвращаем его из колбэка, чтобы продолжить цепочку
  })
  .then(function (response) {
    // этот then сработает, когда разрешится промис с результатами запроса персонажа
    return response.json()
  })
  .then(function (character) {
    renderCharacterProfile(character)
  })
  .catch(function (err) {
    // catch сработает, когда любая из операций выше завершится ошибкой
    renderErrorMessage(err)
  })

```

> `catch` обрабатывает ошибки от всех `then` между ним и предыдущим `catch`.

---

# Promise.all()

Метод `all` — это один из статических методов объекта `Promise`. Метод `all` используют, когда нужно запустить несколько промисов параллельно и дождаться их выполнения.

`Promise.all()` принимает итерируемую коллекцию промисов (чаще всего — массив) и возвращает новый промис, который будет выполнен, когда будут выполнены все промисы, переданные в виде перечисляемого аргумента, или отклонён, если хотя бы один из переданных промисов завершится с ошибкой.

Метод `all` возвращает массив значений всех переданных промисов, при этом сохраняя порядок оригинального (переданного) массива, но не порядок выполнения.

> Если хотя бы один промис из переданного массива завершится с ошибкой, то `Promise.all()` тоже завершится с этой ошибкой.

```javascript
const peopleIds = [1, 13, 3]
arrayFetchUsers = peopleIds.map(user => fetch(`https://swapi.dev/api/people/${user}`).then((response) => response.json()))

Promise.all(arrayFetchUsers)
  .then((responses) => {
    // responses — массив результатов выполнения промисов
    responses.forEach(resp => {
      console.log(resp.name)
    })
  })
  .catch(error => {
    console.error(error)
  })

```

---

# Promise.allSettled()

Метод `allSettled()` — это один из статических методов объекта `Promise`. Его используют, когда нужно запустить несколько промисов параллельно и дождаться их выполнения.

`Promise.allSettled()` очень похож на метод `Promise.all()`, но работает немного по-другому. В отличие от `Promise.all()`, `Promise.allSettled()` ждёт выполнения всех промисов, при этом неважно, завершились они успешно или с ошибкой.

```javascript
const urls = [
  'https://jsonplaceholder.typicode.com/todos/1',
  'https://jsonplaceholder.typicode.org/i_need_an_error',
]
const arrayFetchData = urls.map(url => fetch(url).then(res => res.json()))

Promise.allSettled(arrayFetchData)
  .then((res) => {
    // res — массив результатов выполнения промисов
    res.forEach(item => {
      console.log(item)
    })
  })

```


---


# Promise.race() & Promise.any()

Метод `race()` — это один из статических методов объекта `Promise`. Его используют, чтобы запустить несколько промисов и дождаться того, который выполнится быстрее.

`Promise.race()` принимает итерируемую коллекцию промисов (чаще всего — массив) и возвращает новый промис.
Он завершится, когда завершится самый быстрый из всех переданных. Остальные промисы будут проигнорированы.

> `Promise.race()` завершится, когда завершится самый быстрый из всех переданных промисов. Даже если он завершается с ошибкой.

> `Promise.any()` завершится, когда без ошибки завершится самый быстрый из всех переданных промисов.

---

# Promise.resolve/reject

`Promise.resolve(value)` создаёт успешно выполненный промис с результатом `value`.

Тоже самое

```javascript
let promise = new Promise(resolve => resolve(value));
```

`Promise.reject(error)` создаёт промис, завершённый с ошибкой `error`.

```javascript
let promise = new Promise((resolve, reject) => reject(error));
```

---

# Промисификация

Промисификация – это длинное слово для простого преобразования. Мы берём функцию, которая принимает колбэк и меняем её, чтобы она вместо этого возвращала промис.

Такие преобразования часто необходимы в реальной жизни, так как многие функции и библиотеки основаны на колбэках, а использование промисов более удобно, поэтому есть смысл «промисифицировать» их.

До

```javascript
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Ошибка загрузки скрипта ${src}`));

  document.head.append(script);
}

// использование:
// loadScript('path/script.js', (err, script) => {...})
```

После

```javascript
let loadScriptPromise = function(src) {
  return new Promise((resolve, reject) => {
    loadScript(src, (err, script) => {
      if (err) reject(err)
      else resolve(script);
    });
  })
}

// использование:
// loadScriptPromise('path/script.js').then(...)
```
---

# async/await


Добавленное перед определением функции ключевое слово `async` делает функцию асинхронной. Возвращаемое значение такой функции автоматически оборачивается в `Promise`:

```javascript
async function getStarWarsMovies() {
  return 1
}

console.log(getStarWarsMovies()) // Promise { <state>: "fulfilled", <value>: 1 }

```

Ключевое слово `await` используется, чтобы дождаться выполнения асинхронной операции:

```javascript
async function getStarWarsMovie(id) {
  const response = await fetch(`https://swapi.dev/api/films/${id}/`)
  console.log("ответ получен", response) // *1
  return response.json()
}

const movies = getStarWarsMovie(1).then((movie) => {
  console.log(movie.title)
}) // *2
console.log("результат вызова функции", movies) // *3

```

> Ключевые слова `async/await` не привносят в `JavaScript` что-то новое. Они только упрощают работу с `Promise`.

Без `async/await`

```javascript
function getMainActorProfileFromMovie(id) {
  return fetch(`https://swapi.dev/api/films/${id}/`)
    .then((movieResponse) => {
      return movieResponse.json()
    })
    .then((movie) => {
      const characterUrl = movie.characters[0].split("//")[1]
      return fetch(`https://${characterUrl}`)
    })
    .then((characterResponse) => {
      return characterResponse.json()
    })
    .catch((err) => {
      console.error("Произошла ошибка!", err)
    })
}

getMainActorProfileFromMovie(1).then((profile) => {
  console.log(profile)
})

```
Можно записать с  `async/await`

```javascript
async function getMainActorProfileFromMovie(id) {
  try {
    const movieResponse = await fetch(`https://swapi.dev/api/films/${id}/`);
    const movie = await movieResponse.json();

    const characterUrl = movie.characters[0].split('//')[1];
    const characterResponse = await fetch(`https://${characterUrl}`);
    return characterResponse.json();
  } catch (err) {
    console.error('Произошла ошибка!', err);
  }
}

getMainActorProfileFromMovie(1).then((profile) => {console.log(profile)});

```

Такой код проще понимать:

- он плоский
- выглядит, как синхронный
- использует стандартный `try...catch` блок для обработки ошибок

---

# Обработка исключений


Конструкция `try...catch` позволяет выполнить произвольный код, но если в нем произошла ошибка, то программа не остановит своё выполнение, а перейдёт в блок `catch`, где ошибку можно обработать.

Чтобы использовать `try...catch`, необходимо в блоке `try` написать код, который нужно исполнить, а в блоке `catch` написать, что делать в случае ошибки.

```javascript
try {
  someFunction()
  anotherFunction()
} catch (err) {
  console.log("Поймали ошибку! Вот она: ", err.message)
}

```

> Если в блоке `try` не произошло ошибок, то код в блоке `catch` не выполнится.

> Важно помнить, что код в `try` должен быть `синтаксически верным`. Если написать невалидный код, то скрипт не запустится, потому что JavaScript не поймёт код. Ошибки, которые обработает блок `catch`, будут ошибками `во время выполнения` программы.

---

# finally

В конструкцию `try...catch` можно добавить блок `finally`, который выполнится после блоков `try` и `catch.` Неважно какой код выполнился в предыдущих блоках, после их завершения (даже если из `catch` была выброшена новая ошибка) исполнится код в блоке `finally`.


```javascript
try {
  webSocket.connect("ws://....")

  callMayThrowError()
} catch (err) {
  // Здесь тоже может возникнуть ошибка
  doSomeWithError(err)
} finally {
  // Выполнится всегда
  webSocket.disconnect("ws://....")
}

```
---

# Оператор «throw»

Оператор `throw` генерирует ошибку.

```javascript
let error = new Error(message);
// или
let error = new SyntaxError(message);
let error = new ReferenceError(message);



throw error;

```